### ISSUE TITLE
Suggestion: User System.import/require.insure

### ISSUE THREAD

**Issue by dlebedynskyi** [ctrlplusb/code-split-component#12]
Currently you have to use code split as 
```
<Match
  pattern="/about"
  render={routerProps =>
    <CodeSplit chunkName="about" modules={{ About: require('./About') }}>
      { ({ About }) => About && <About {...routerProps} /> }
    </CodeSplit>
  }
/>
```
this makes require call directly in code. Instead it would be great to use more traditional `require.ensure` or webpack 2 `System.import`.

**Comment by ctrlplusb** [comment]
Hi @dlebedynskyi;

Yes this is by design.  If you reference the code-split-component docs you will see it uses a babel plugin to transpile this code into require.ensure statements as and when needed.  There are times when you don't want it to create chunks and load asynchronously (dev or SSR).

I like having `require` statements being the default as your eslint etc plugins will ensure you are pulling in a correct module, and in the cases that you just don't include the babel or webpack plugins that code-split-component requires then it will just fall back into standard synchronous loading behaviour.

Hope this makes it more clear. :)

**Comment by dlebedynskyi** [comment]
@ctrlplusb  I see.  makes it a bit cleaner true. Did not saw it in docs so decided to ask. 
NOTE: since you already use babel to transform this - there is also 

https://github.com/thgreasi/babel-plugin-system-import-transformer

atm my linter rather complains on  global-require rule.
